//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.LocationV2.Entities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.LocationV2.Entities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of ID must be between 2 to 12!.
        /// </summary>
        internal static string idLength {
            get {
                return ResourceManager.GetString("idLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID is required!.
        /// </summary>
        internal static string idRequired {
            get {
                return ResourceManager.GetString("idRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format!.
        /// </summary>
        internal static string invalidDateFormat {
            get {
                return ResourceManager.GetString("invalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of LocationID must be between 2 to 9!.
        /// </summary>
        internal static string locIdLength {
            get {
                return ResourceManager.GetString("locIdLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationID is required!.
        /// </summary>
        internal static string locIdRequired {
            get {
                return ResourceManager.GetString("locIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length must be between 2 to 100!.
        /// </summary>
        internal static string locNameLength {
            get {
                return ResourceManager.GetString("locNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location name is required!.
        /// </summary>
        internal static string locNameRequired {
            get {
                return ResourceManager.GetString("locNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date can not be later than modified date.
        /// </summary>
        internal static string validateCreatedDate {
            get {
                return ResourceManager.GetString("validateCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of CountryID or ID does not match its CountryID!.
        /// </summary>
        internal static string validateFormatCountryID {
            get {
                return ResourceManager.GetString("validateFormatCountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of DID or ID does not match its DID!.
        /// </summary>
        internal static string validateFormatDID {
            get {
                return ResourceManager.GetString("validateFormatDID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullAddress must start with LocationName!.
        /// </summary>
        internal static string validateFullAddress {
            get {
                return ResourceManager.GetString("validateFullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of ID does not match its kind!.
        /// </summary>
        internal static string validateLengthID {
            get {
                return ResourceManager.GetString("validateLengthID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of ParentID or ID does not match its ParentID!.
        /// </summary>
        internal static string validateParentID {
            get {
                return ResourceManager.GetString("validateParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of PID or ID does not match its PID!.
        /// </summary>
        internal static string validatePID {
            get {
                return ResourceManager.GetString("validatePID", resourceCulture);
            }
        }
    }
}
