//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.LocationV2.Webhook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.LocationV2.Webhook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebhookEventError.
        /// </summary>
        internal static string collectionEventError {
            get {
                return ResourceManager.GetString("collectionEventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebhookSubscription.
        /// </summary>
        internal static string collectionSubscription {
            get {
                return ResourceManager.GetString("collectionSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address has been deleted!.
        /// </summary>
        internal static string deleteMeg {
            get {
                return ResourceManager.GetString("deleteMeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new address added!.
        /// </summary>
        internal static string insertMeg {
            get {
                return ResourceManager.GetString("insertMeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Timeout.
        /// </summary>
        internal static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address has been changed!.
        /// </summary>
        internal static string updateMeg {
            get {
                return ResourceManager.GetString("updateMeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook Send Request Failed.
        /// </summary>
        internal static string webhookSendFail {
            get {
                return ResourceManager.GetString("webhookSendFail", resourceCulture);
            }
        }
    }
}
