//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISALocationV2.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISALocationV2.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc gia.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/ Huyện.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationSynch.
        /// </summary>
        public static string DownloadName {
            get {
                return ResourceManager.GetString("DownloadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hết hiệu lực.
        /// </summary>
        public static string ExpridMeg {
            get {
                return ResourceManager.GetString("ExpridMeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ID mới.
        /// </summary>
        public static string Header_ID {
            get {
                return ResourceManager.GetString("Header_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp.
        /// </summary>
        public static string Header_Kind {
            get {
                return ResourceManager.GetString("Header_Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ID cũ.
        /// </summary>
        public static string Header_LocID {
            get {
                return ResourceManager.GetString("Header_LocID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên địa chỉ.
        /// </summary>
        public static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cha.
        /// </summary>
        public static string Header_ParentID {
            get {
                return ResourceManager.GetString("Header_ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is active!.
        /// </summary>
        public static string HealthzMeg {
            get {
                return ResourceManager.GetString("HealthzMeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string HeathzStatus {
            get {
                return ResourceManager.GetString("HeathzStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/ Thành phố.
        /// </summary>
        public static string Privince {
            get {
                return ResourceManager.GetString("Privince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string SheetName {
            get {
                return ResourceManager.GetString("SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string STT {
            get {
                return ResourceManager.GetString("STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xã/ Phường.
        /// </summary>
        public static string Ward {
            get {
                return ResourceManager.GetString("Ward", resourceCulture);
            }
        }
    }
}
